"""add error_message and updated_at to scans

Revision ID: 6d9a43456f33
Revises: 0ed715fbb4e4
Create Date: 2026-08-03 00:30:22.816018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9a43456f33'
down_revision: Union[str, Sequence[str], None] = '0ed715fbb4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('scans', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'error_message')
    op.drop_column('scans', 'updated_at')
    # ### end Alembic commands ###
